#import "@preview/polylux:0.4.0": *

#set page(paper: "presentation-16-9")
#set text(size: 20pt, font: "Maple Mono NF")
#let custom_icon = path => box(baseline: 6pt)[#image("assets/" + { path }, width: 1em)]

#let nix = box(baseline: 3pt)[#image("assets/nix.svg", height: 1em)]
#let col1 = rgb("b68dc3")
#let col3 = rgb(245, 169, 184)
#let col2 = rgb("695988")
#let green1 = rgb("5ec39a")

#slide[
  #set page(fill: col1)
  #set text(fill: white, size: 35pt)
  #set align(horizon + center)
  = (｡ι‿ι｡) NixOS-secrets
]

#slide[
  #set align(horizon)
  #set text(size: 25pt)
  = Who am I?
  #v(0.5em)
  #set text(size: 25pt)

  - `@prescientmoon`
  - https://moonythm.dev
  #show: later
  - Math :O
  - GSOC.
]

#slide[
  #set text(size: 25pt)
  = What is this?
  #v(0.5em)
  #set text(size: 20pt)

  // - Previously worked on by Lassulus, clan, vars, etc
  // - Worked on this for GSOC
  // - Only one week to prepare this presentation, so a tad bit rushed

  #show: later
  - Unified interface for managing secrets.
  - Pluggable backend system.
  #show: later
  - Formerly `nixos-vars` (see: clan).
  #show: later
  - CLI, #nix NixOS module & beyond :O
  - Very experimental (read: might break).
]

#slide[
  #set align(center)
  #image("assets/standards.png", height: 100%)
]

#slide[
  #set text(size: 25pt)
  = The structure of a secret
  #v(0.5em)
  #set text(size: 22pt)

  // Think of public / private keys as an example of a secret that holds more than one!
  - A secret holds a non-empty set of files.
  - Backends!

  #show: later
  #v(0.5em)
  #set align(horizon + center)
  #set text(size: 20pt)
  ```nix
  {
    secrets.store.cat = {
      backend = "plain";
      files.greeting = { };
    };
  }
  ```
]

#slide[
  #set text(size: 25pt)
  = Generators
  #v(1em)
  #set text(size: 20pt)

  // Example usecases: machine IDs, SSH keys, etc
  Secrets can be generated by a script, no way!

  #set text(size: 20pt)
  #v(1em)
  #set align(horizon + center)
  ```nix
  {
    secrets.store.cat = {
      # ...
      generate = pkgs: pkgs.writeScript "gen-user" ''
        #!/bin/sh
        echo "Meow~" > "$out/greeting"
      '';
    };
  }
  ```
  // - The script writes the value of the secret to $out
  // - This is not simply a script!
  // - Explain host/target system
  // - Language agnostic
]

#slide[
  #set text(size: 25pt)
  = Dependencies :O
  #v(1em)
  #set text(size: 20pt)

  Secrets can depend on each other!

  #v(1em)
  #set align(horizon + center)
  #set text(size: 18pt)
  ```nix
  {
    secrets.store.cow = {
      dependencies = [ "cat" ];
      files.cow-greeting = { };
      generate = pkgs: pkgs.writeScript "gen-derived" ''
        #!/bin/sh
        export PATH="${lib.makeBinPath [ pkgs.coreutils pkgs.cowsay ]}"
        cat $in/cat/greeting | cowsay > $out/cow-greeting
      '';
    };
  }
  ```
  // - Read from $in
  // - Magic
  // - Dependencies work across Nixcon
]

#slide[
  #set text(size: 25pt)
  = Prompts?!
  #v(1em)
  #set text(size: 20pt)

  User input? It's more likely than you think!

  #show: later
  #set text(size: 18pt)
  #set align(horizon + center)
  ```nix
  {
    secrets.store.user = {
      prompts.name = {
        backend = "simple";
        label = "Your name";
        description = "The person to address the greeting to";
        type = "line";
      };

      # ...
    };
  }
  ```
]

#slide[
  #set text(size: 25pt)
  = Prompts?! (2)
  #v(1em)
  #set text(size: 20pt)

  User input? It's more likely than you think!

  #v(1em)
  #set text(size: 18pt)
  #set align(horizon + center)
  ```nix
  {
    secrets.store.user = {
      # ...
      files.greeting = { };
      generate = pkgs: pkgs.writeScript "gen-user" ''
        #!/bin/sh
        export PATH="${lib.makeBinPath [ pkgs.coreutils ]}"
        echo "Hi! My name is $(cat "$prompts/name")." > "$out/greeting"
      '';
    };
  }
  ```
]

#slide[
  #set page(margin: 0cm)
  #image("assets/lilith.jpg", height: 100%)
]

#slide[
  #set page(fill: col2)
  #set text(fill: white)
  #align(horizon + center)[
    #set text(size: 35pt)
    = Act 2: Backends
  ]

  #align(center + bottom)[
    I guess we're doing acts now...
  ]
]

// #slide[
//   #set align(horizon)
//
//   = What are they?
//   #v(1em)
//   #set text(size: 23pt)
//
//   - Store & prompt backends.
// ]

#slide[
  = Prompt backends
  #v(0.5em)
  #set text(size: 19pt)

  - Ask!
  - Given `secret-name`, `prompt-name`, `prompt-type`, `prompt-label`, and `prompt-description`; writes to `$out`.
  #show: later
  ```nix
      {
        secrets.backends.prompt.simple.ask = pkgs:
          pkgs.writeScript "simple-prompt" ''
            #!/bin/sh
            export PATH="${lib.makeBinPath [ pkgs.coreutils ]}"
            if [[ "$3" == "line" ]]; then
              read -rp "$4: " text
              echo -n "$text" > "$out"
            # ...
          '';
      }
  ```
]

#slide[
  #set align(horizon)
  = Store backends
  #v(1em)
  #set text(size: 18pt)

  - Actual secret storage.
  - Can also handle deployment (when needed).
  // - `secrets.backends.store.simple.<script>`
]

#slide[
  = Get
  #v(0.5em)
  #set text(size: 18pt)

  - Takes a secret and file name, writes the content to `$out`

  #v(2em)
  #show: later
  = Set
  #v(0.5em)
  #set text(size: 18pt)

  - Takes a secret and file name, writes the content of `$in` to the secret.

  #v(2em)
  #show: later
  = List
  #v(0.5em)
  #set text(size: 18pt)

  - Produces a list of all the `secret, file` pairs stored by the backend.
  - Some might be stale — useful for garbage collection!
]

#slide[
  #set align(horizon)
  = Delete
  #v(1em)
  #set text(size: 20pt)

  - Deletes the given `secret, file` pair.

  #show: later
  #v(1em)
  = Fixup
  #v(1em)
  #set text(size: 20pt)

  - Invoked for every secret (on each run).
]

#slide[
  #set align(horizon)
  = Deployments
  #v(0.5em)
  #set text(size: 18pt)

  // The traditional way
  #show: later

  - `deploy.remote` (whatever you want, really).
  - `deploy.local` (the current machine, live CDs, etc).

  #show: later
  #v(2em)
  = Extensibility
  #v(0.5em)

  - Backends (of any kind) can just... add options!
  // as they say, "you can just do things"
]

#slide[
  #set page(fill: col3)
  #set text(fill: white)
  #align(horizon + center)[
    #set text(fill: white, size: 35pt)
    = Act 3: the CLI
  ]

  // - Not a tutorial
  // - Will quickly go over the capabilities

  #align(center + bottom)[
    3 as in :3
  ]
]

#slide[
  #set align(horizon)

  = The CLI's input:
  #v(1em)
  #set text(size: 20pt)

  - #nix Nix files / flakes.
  #show: later
  - can take unevaluated #nix NixOS configurations.
  - can take evaluated #nix NixOS configurations (ala flakes).
  #show: later
  - can take #nix Nix data matching a specific schema.
  - can take JSON. // There's a schema!
]

#slide[
  #set align(horizon)
  = Generating the secrets
  #v(1em)
  #set text(size: 20pt)

  - `nixos-secrets generate`
  - `nixos-secrets generate --set secret=path/to/stuff`
  - `nixos-secrets generate --generate secret`

  #show: later
  #v(2em)
  = Other commands
  #v(1em)
  #set text(size: 20pt)

  - `collect-garbage`
  #show: later
  - `deploy`
]

#slide[
  #set page(margin: 0cm)
  #image("assets/lilith.jpg", height: 100%)
]

#slide[
  #set page(fill: col1)
  #set text(fill: white)
  #align(horizon + center)[
    #set text(fill: white, size: 35pt)
    = Act 4: Behind the scenes
  ]

  #align(center + bottom)[
    How high will the counter go?
  ]
]

#let lunal = custom_icon("cozyluna.webp")
#let lunar = custom_icon("cozyluna.png")
#slide[
  #set page(margin: (bottom: 0cm, right: 0.5cm))
  = #lunal Stuff can go wrong D: #lunar
  #v(1em)
  #set text(size: 18pt)

  #show: later
  1. Declare secrets A and B. B depends on A.
  2. Generate them successfully!
  #show: later
  3. Tweak A's script, run the CLI with `--generate a`.
  4. Oh no! B's script has a bug that makes it crash :(
  #show: later
  5. Fix the bug & run the CLI without `--generate a`.
  6. No reason for the CLI to update B; inconsistent state :(

  #set align(right + bottom)
  #image("assets/grayno.webp", height: 6.5cm)
]
#slide[
  = Metadata
  #v(1em)
  #set text(size: 18pt)

  - Each secret has a metadata file attached to it.
  - Looks like any other file to the secret.
  #show: later
  - No more bad states!$""^(1, 2, 3, 4, 5)$

  #set align(right + bottom)
  #image("assets/graycool.webp", height: 6cm)
]

#slide[
  #set page(fill: col2)
  #set text(fill: white)
  #align(horizon + center)[
    #set text(fill: white, size: 35pt)
    = Act 5: The state of secrets
  ]

  #align(center + bottom)[
    Is it just me, or are the acts getting shorter?
  ]
]

#slide[
  #set align(horizon)
  = Example backends
  #v(1em)
  #set text(size: 22pt)

  - No production-ready backend (write your own!).
  #show: later
  - A simple prompt backend.
  - A testing prompt backend.
  #show: later
  - A failing store backend.
  - A plain-text store backend.
  - An age-based store backend.
]

#let tail = custom_icon("angrytai.webp")
#let tair = custom_icon("angrytai.png")
#slide[
  #set align(horizon)
  = #tail Missing stuff #tair
  #v(1em)
  #set text(size: 20pt)

  - Production backend.
  - User/group/permissions.
  - Home manager integration.
  - The `--edit` flag.
]

#slide[
  #set page(fill: col3)
  #set text(fill: white)
  #align(horizon + center)[
    #set text(fill: white, size: 35pt)
    = Act 6: Conclusion?
  ]

  #align(center + bottom)[
    The last one :O
  ]
]

// #slide[
//   #set align(horizon)
//   = Consequences of the backend system
//   #v(1em)
//   #set text(size: 20pt)
//
//   - Sharing prompts.
//   - `neededForUsers`
//   - Half-public & half-private "secrets".
// ]

#slide[
  #set align(horizon)
  = Thank you
  #v(1em)

  - Ask questions!
  - Read through the docs & point out anything that's confusing.
  - Try switching (a tiny part) of your config to `nixos-secrets`.
  - Write a custom backend! (for example one that deploys via the Nix store)
  // - Nixpkgs PR `#547171`.
]

#slide[
  - Link to cheatsheet here (with QR code).
]

#slide[
  #set page(margin: -0.05cm)
  #image("assets/lilith.jpg", height: 100%)
]
